const bool debug = false;
const uint8_t tokenProtocolDelay = 2;

#define DATAPIN_TOP_READ PINB2
#define DATAPIN_TOP_READ_REG PINB
#define DATAPIN_TOP_WRITE PORTB2
#define DATAPIN_TOP_WRITE_REG PORTB

#define DATAPIN_TOP_INTERRUPT PCINT10
#define DATAPIN_TOP_INTERRUPT_REG PCMSK1
#define DATAPIN_TOP_INTERRUPT_GIMSK PCIE1

#define CLOCKPIN_TOP_INTERRUPT PCINT7
#define CLOCKPIN_TOP_INTERRUPT_REG PCMSK0
#define CLOCKPIN_TOP_INTERRUPT_GIMSK PCIE0