const bool debug = false;
const double tokenProtocolDelay = 0.5;

#define DATAPIN_TOP_READ 5
#define DATAPIN_TOP_READ_REG PORTA_IN
#define DATAPIN_TOP_WRITE 5
#define DATAPIN_TOP_WRITE_REG PORTA_OUT
#define DATAPIN_TOP_OUTPUT_REG PORTA_DIR
#define DATAPIN_TOP_OUTPUT 5

#define DATAPIN_TOP_INTERRUPT 0
#define DATAPIN_TOP_INTERRUPT_REG PORTA_PIN5CTRL

#define CLOCKPIN_TOP_INTERRUPT 0
#define CLOCKPIN_TOP_INTERRUPT_REG PORTA_PIN4CTRL

#define DATAPIN_BOTTOM_OUTPUT 1
#define DATAPIN_BOTTOM_PIN_OUTPUT_REG PORTA_DIR
#define DATAPIN_BOTTOM_WRITE 1
#define DATAPIN_BOTTOM_WRITE_REG PORTA_OUT
#define DATAPIN_BOTTOM_READ 1
#define DATAPIN_BOTTOM_READ_REG PORTA_IN

#define CLOCKPIN_BOTTOM_OUTPUT 3
#define CLOCKPIN_BOTTOM_PIN_OUTPUT_REG PORTA_DIR
#define CLOCKPIN_BOTTOM_WRITE 3
#define CLOCKPIN_BOTTOM_WRITE_REG PORTA_OUT

#define FAILEDAMOUNT 20
